import { StyleSheet } from '@react-pdf/renderer';

// Paleta de colores corporativa de Relats y Mappa
export const pdfStyles = StyleSheet.create({
  page: {
    padding: 44,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
    color: '#1E293B',
    fontSize: 9,
    lineHeight: 1.5,
  },
  header: {
    borderBottomWidth: 2,
    borderBottomColor: '#0D2C54',
    paddingBottom: 12,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'column',
    flex: 1,
  },
  headerLogos: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoImg: {
    height: 24,
    objectFit: 'contain',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#0D2C54',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 8,
    color: '#C3002F',
    fontWeight: 'bold',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  gridContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  card: {
    flex: 1,
    padding: 12,
    borderRadius: 4,
    backgroundColor: '#F8FAFC',
    borderLeftWidth: 3,
  },
  cardLabel: {
    fontSize: 7,
    color: '#64748B',
    textTransform: 'uppercase',
    fontWeight: 'bold',
    marginBottom: 4,
  },
  cardValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0F172A',
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#0D2C54',
    marginBottom: 8,
    marginTop: 10,
  },
  chartPlaceholder: {
    height: 140,
    backgroundColor: '#F1F5F9',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  placeholderText: {
    fontSize: 9,
    color: '#64748B',
    fontStyle: 'italic',
  },
  table: {
    width: '100%',
    marginTop: 5,
    marginBottom: 15,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#0D2C54',
    padding: 6,
    borderRadius: 2,
  },
  tableHeaderCell: {
    fontSize: 8,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    padding: 6,
    alignItems: 'center',
  },
  tableCell: {
    fontSize: 8,
    color: '#334155',
  },
  recommendationBox: {
    marginTop: 10,
    padding: 12,
    backgroundColor: '#FFF1F2',
    borderRadius: 4,
    borderLeftWidth: 3,
    borderLeftColor: '#C3002F',
  },
  recommendationTitle: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#C3002F',
    marginBottom: 4,
  },
  recommendationText: {
    fontSize: 8,
    color: '#475569',
    lineHeight: 1.4,
    textAlign: 'justify',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 44,
    right: 44,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 7,
    color: '#94A3B8',
  },
});